"""Initial migration

Revision ID: 05e09251a800
Revises: 681c040def2b
Create Date: 2022-05-07 12:15:59.822280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e09251a800'
down_revision = '681c040def2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('questions', 'id_question',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'id_question',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('questions', 'id')
    # ### end Alembic commands ###
