"""Initial migration

Revision ID: 0d779b9ccf44
Revises: e34dd31adbb8
Create Date: 2022-05-07 01:35:54.867505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d779b9ccf44'
down_revision = 'e34dd31adbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('date_add_in_db', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'date_add_in_db')
    # ### end Alembic commands ###
