"""Initial migration

Revision ID: d4d95d35612a
Revises: 
Create Date: 2022-05-05 13:43:42.686205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4d95d35612a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('text_answer', sa.String(length=250), nullable=False))
    op.add_column('questions', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('questions', 'data')
    op.drop_column('questions', 'id_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('id_answer', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('questions', 'date')
    op.drop_column('questions', 'text_answer')
    # ### end Alembic commands ###
